name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DATABASE_URL: "postgresql://postgres:<DATABASE_URL>:5432/postgres"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.8.0] # You can specify more versions for a matrix build if needed

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci # This command is similar to `npm install`, but it's meant for automated environments like CI

    - name: Run TypeScript type checker
      run: npx tsc --noEmit # This command checks types without emitting output files

    - name: Run Lint
      run: npm run lint # This assumes you have a "lint" script specified in your package.json
